env:
  global:
    - CC_TEST_REPORTER_ID=ad7d02c4a09f9f9845a84380473e215749292d230080f259395093b25a2b04a4
language: nix
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - nix-shell dev-shell.nix --command 'echo Downloaded deps'
  - nix-shell dev-shell.nix --command './autogen.sh --prefix=$PREFIX && make && make install && pytest --cov=redditisgtk'
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
